require 'musicality/version'

require 'musicality/core/event'
require 'musicality/core/hash_make'
require 'musicality/core/pitch'
require 'musicality/core/note'
require 'musicality/core/sequence'
require 'musicality/core/transition'
require 'musicality/core/dynamic'
require 'musicality/core/tempo'
require 'musicality/core/instrument'
require 'musicality/core/part'
require 'musicality/core/program'
require 'musicality/core/score'

require 'musicality/util/pitch_constants'
require 'musicality/util/score_file'
require 'musicality/util/class_finder'
require 'musicality/util/dynamic_computer'
require 'musicality/util/tempo_computer'
require 'musicality/util/note_time_converter'
require 'musicality/util/piecewise_function'

require 'musicality/performance/sequencer'
require 'musicality/performance/performer'
require 'musicality/performance/conductor'
require 'musicality/performance/instruments/oscillator'
require 'musicality/performance/instruments/sawtooth_wave'
require 'musicality/performance/instruments/sine_wave'
require 'musicality/performance/instruments/square_wave'
require 'musicality/performance/instruments/triangle_wave'

