# basic core classes
require 'music-transcription/version'
require 'music-transcription/validatable'
require 'music-transcription/errors'

# code for transcribing (representing) music
require 'music-transcription/pitch'
require 'music-transcription/pitches'
require 'music-transcription/link'
require 'music-transcription/articulations'
require 'music-transcription/note'
require 'music-transcription/dynamics'
require 'music-transcription/change'
require 'music-transcription/part'
require 'music-transcription/program'
require 'music-transcription/tempo'
require 'music-transcription/meter'
require 'music-transcription/meters'
require 'music-transcription/score'

require 'treetop'
require 'music-transcription/parsing/nonnegative_integer'
require 'music-transcription/parsing/positive_integer'
#require 'music-transcription/parsing/articulation'
#require 'music-transcription/parsing/articulation_nodes'
#require 'music-transcription/parsing/pitch'
#require 'music-transcription/parsing/pitch_node'
#require 'music-transcription/parsing/link'
#require 'music-transcription/parsing/link_node'
#require 'music-transcription/parsing/duration'
#require 'music-transcription/parsing/duration_nodes'
#require 'music-transcription/parsing/note'
#require 'music-transcription/parsing/note_nodes'
