require 'musicality/version'

require 'musicality/core/event'
require 'musicality/core/hash_make'
require 'musicality/core/plugin_config'
require 'musicality/core/unique_token'

require 'musicality/model/pitch'
require 'musicality/model/note'
require 'musicality/model/sequence'
require 'musicality/model/dynamic'
require 'musicality/model/tempo'
require 'musicality/model/part'
require 'musicality/model/program'
require 'musicality/model/score'

require 'musicality/util/pitch_constants'
require 'musicality/util/score_file'
require 'musicality/util/class_finder'
require 'musicality/util/piecewise_function'
require 'musicality/util/dynamic_computer'
require 'musicality/util/tempo_computer'
require 'musicality/util/score_collator'
require 'musicality/util/note_time_converter'

require 'musicality/performance/sequencer'
require 'musicality/performance/performer'
require 'musicality/performance/arrangement'
require 'musicality/performance/arranger'
require 'musicality/performance/conductor'
#require 'musicality/performance/instruments/adsr_instrument'
require 'musicality/performance/instruments/oscillator'
require 'musicality/performance/instruments/sawtooth_wave'
require 'musicality/performance/instruments/sine_wave'
require 'musicality/performance/instruments/square_wave'
require 'musicality/performance/instruments/triangle_wave'

